### ISSUE TITLE
error when lauch

### ISSUE THREAD

**Issue by yesyeahvh123** [dotRelith/even-faster-stable-diffusion#3]
i get error please fix it 
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.6. Please reinstall the torchvision that matches your PyTorch install.

**Comment by dotRelith** [comment]
fixing it

**Comment by dotRelith** [comment]
@yesyeahvh123 I think it's fixed. please let me know if you get any error.

**Comment by yesyeahvh123** [comment]
sir i get this error when complete general bulk image, this problem in new web ui version, old version of camendurunot have this error , but I'm not satisfied with the result of the general image in the old version
![Capture](https://user-images.githubusercontent.com/69633089/213713801-0306b9a7-a17b-44ce-90b9-3e3954327016.PNG)
